defaults:
  - model: espcn

dataset:
  train_data_path: "data/train"
  original_val_data_path: "data/validation/original"
  quarter_val_data_path: "data/validation/0.25x"


train:
  learning_rate: 1e-3
  batch_size: 10
  num_workers: 0
  num_epoch: 1
  milestones: [30, 50, 65, 80, 90]
  gamma: 0.7
  log_dir: log/
  output_dir: output/
  use_gpu: true

wandb:
  project_name: "super_res_model_comparison"