defaults:
  - _self_
  - model: espcn
  - loss: mseloss
  - optimizer: adam
  - scheduler: steplr
  - datamodule: bicubic
  - experiment: null

train:
  batch_size: 8
  num_workers: 0
  num_epoch: 40
  log_dir: log/
  output_dir: models/espcn/
  weights_path: null
  ssim_loss_alpha: null

wandb:
  project: "super-res-model-comparison"
  name: "espcn-40-epochs"