defaults:
  - _self_
  - model: espcn
  - loss: mseloss
  - optimizer: adam
  - scheduler: steplr
  - experiment: null

train:
  batch_size: 10
  num_workers: 0
  num_epoch: 40
  log_dir: log/
  output_dir: models/espcn/
  weights_path: null
  ssim_loss_alpha: null

dataset:
  train_data_path: "data/train"
  original_val_data_path: "data/validation/original"
  quarter_val_data_path: "data/validation/0.25x"

wandb:
  project: "super-res-model-comparison"
  name: "espcn-40-epochs"